logging:
  root_log_level: INFO
  # When running in k8s, use JSON logger via env setting
  # formatter: json
  formatter: "standard"
  child_log_levels:
    mchpy: INFO
app_name: Flexpart IFS Preprocessor
