logging:
  root_log_level: INFO
  # When running in k8s, use JSON logger via env setting
  # formatter: json
  formatter: "standard"
  child_log_levels:
    mchpy: INFO
app_name: Flexpart IFS Preprocessor
main:
  source_role_arn: SOURCE_ROLE_ARN
  source_s3_bucket_arn: SOURCE_S3_BUCKET_ARN
  target_s3_bucket_name_europe: target-bucket-europe
  target_s3_bucket_name_global: target-bucket-global
  dynamodb_table_name: db-table
